################## Register User ######################
POST https://localhost:7282/api/auth/register HTTP/1.1
content-type: application/json

{
    "username":"boyy",
    "email": "boy@email.com",
    "phoneNumber":"09129876543",
    "password":"1234@Boy"
}


################## Login User ######################
POST https://localhost:7282/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "mehf@email.com",
    "password":"12345@Boy"
}

################## Refresh token ######################
POST https://localhost:7282/api/auth/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmRlYmNjNC1mYjI2LTRmY2ItNTJhZi0wOGRkZTlhOWU4MWYiLCJlbWFpbCI6Im1laGZAZW1haWwuY29tIiwianRpIjoiZmE0NWVmMmYtNjc1OS00MzJhLTgwY2QtNTcyN2E3NTlhNmJjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1Njg1OTcyOCwiaXNzIjoiUFRNIiwiYXVkIjoiUFRNLkNsaWVudHMifQ.RaKj05h1xh0QPzwmpKPiOcgYnySPTHKDbKVyPSNTSbI
{
    "refreshToken":"f04f656430b94a36a4c5390efa252877.TpcrozPKuC8geQhMYbsmQ7neU7jCbh2tK+dHiXyf2oM="
}

################## Logout User ######################
POST https://localhost:7282/api/auth/logout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmRlYmNjNC1mYjI2LTRmY2ItNTJhZi0wOGRkZTlhOWU4MWYiLCJlbWFpbCI6Im1laGZAZW1haWwuY29tIiwianRpIjoiNDJmYTRmZTMtODNmNS00ODFmLTlmM2EtZTVmZDUwZjdiNzgzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1NzA0NTA0NCwiaXNzIjoiUFRNIiwiYXVkIjoiUFRNLkNsaWVudHMifQ.1gySGD3BvOvXMFHE2sb5qQYGn1CHqCrK1yKMv48iHxU



