
################## Create Free ######################
POST http://localhost:5262/api/plan HTTP/1.1
content-type: application/json

{
    "title": "free",
    "description": "free plan",
    "price":0,
    "maxTasks":5,
    "durationDays":7
}

################## Create Premium ######################
POST http://localhost:5262/api/plan HTTP/1.1
content-type: application/json

{
    "title": "premium",
    "description": "premium plan",
    "price":9,
    "maxTasks":100,
    "durationDays":30
}

################## Create Business ######################
POST http://localhost:5262/api/plan HTTP/1.1
content-type: application/json

{
    "title": "business",
    "description": "business plan",
    "price":50,
    "durationDays":365
}

################## Get By Id ######################

GET  https://localhost:7282/api/Plan/03b17659-ddd4-4824-8fed-08dde4aed35c HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmRlYmNjNC1mYjI2LTRmY2ItNTJhZi0wOGRkZTlhOWU4MWYiLCJlbWFpbCI6Im1laGZAZW1haWwuY29tIiwianRpIjoiZmE0NWVmMmYtNjc1OS00MzJhLTgwY2QtNTcyN2E3NTlhNmJjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1Njg1OTcyOCwiaXNzIjoiUFRNIiwiYXVkIjoiUFRNLkNsaWVudHMifQ.RaKj05h1xh0QPzwmpKPiOcgYnySPTHKDbKVyPSNTSbI


################## Get All #######################

GET  https://localhost:7282/api/plan HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmRlYmNjNC1mYjI2LTRmY2ItNTJhZi0wOGRkZTlhOWU4MWYiLCJlbWFpbCI6Im1laGZAZW1haWwuY29tIiwianRpIjoiZmE0NWVmMmYtNjc1OS00MzJhLTgwY2QtNTcyN2E3NTlhNmJjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1Njg1OTcyOCwiaXNzIjoiUFRNIiwiYXVkIjoiUFRNLkNsaWVudHMifQ.RaKj05h1xh0QPzwmpKPiOcgYnySPTHKDbKVyPSNTSbI


################## Update ######################
PUT  http://localhost:5262/api/plan/b3146397-e456-4f8c-291e-08dde5bdeabd HTTP/1.1
content-type: application/json

{
    "title": "free",
    "description": "free plan",
    "price":0,
    "maxTasks":7
}
################## Update with validation Error ######################
PUT  http://localhost:5262/api/plan/b3146397-e456-4f8c-291e-08dde5bdeabd HTTP/1.1
content-type: application/json

{
    "title": "free",
    "description": "free plan",
    "price":0,
    "maxTasks":15
}


################## Deactive ######################
PATCH   http://localhost:5262/api/plan/c0e855de-6851-406c-7861-08dde32e1dac/deactive HTTP/1.1
content-type: application/json


################## Deactive ######################
PATCH   http://localhost:5262/api/plan/c0e855de-6851-406c-7861-08dde32e1dac/active HTTP/1.1
content-type: application/json

