


################## Get All ######################
GET  http://localhost:5262/api/user HTTP/1.1
content-type: application/json

################## Get By Id ######################
GET  http://localhost:5262/api/user/d7d8c4f2-ef1d-4c8e-f1bf-08dde86b3faa HTTP/1.1
content-type: application/json


################## Update ######################
PUT  http://localhost:5262/api/user/ff4d7ff7-15e5-4bc3-4d82-08dde4f760e4 HTTP/1.1
content-type: application/json

{
    "username":"boy",
    "email": "boy2up@email.com",
    "phoneNumber":"09129876543"
}
